@startuml

title __ROBOT's Class Diagram__\n




  package  {
    package com.company {
      class ApplicationProperties {
      }
    }
  }



  package  {
    package com.company {
      package com.company.navigation {
        class GraphManager {
        }
      }
    }
  }


  package  {
    package com.company {
      package com.company.navigation {
        class GraphViewer {
        }
      }
    }
  }


  package  {
    package com.company {
      package com.company.navigation {
        class GridLayout {
        }
      }
    }
  }




  package  {
    package com.company {
      class MainRobot {
      }
    }
  }


  package  {
    package com.company {
      package com.company.navigation {
        class MapGraph {
        }
      }
    }
  }



  package  {
    package com.company {
      package com.company.comms {
        class MessagePayload {
        }
      }
    }
  }


  package  {
    package com.company {
      package com.company.comms {
        class MessageRecordParser {
        }
      }
    }
  }


  package  {
    package com.company {
      package com.company.comms {
        class MessageRecordQueue {
        }
      }
    }
  }




  package  {
    package com.company {
      class MonitorThread {
      }
    }
  }



  package  {
    package com.company {
      package com.company.comms {
        class SeriaListener {
        }
      }
    }
  }


  package  {
    package com.company {
      package com.company.comms {
        class SerialMessageRecord {
        }
      }
    }
  }




  package  {
    package com.company {
      class WriteThread {
      }
    }
  }
  package {
    package imports{
       class JFrame
       class edu.uci.ics.jung.graph.SparseMultigraph
       class edu.uci.ics.jung.graph.Graph
       class Thread
       class StaticLayout
       class Dimension
       class VisualizationViewer
       class com.fazecast.jSerialComm.SerialPortPacketListener
       class com.fazecast.jSerialComm.SerialPort
       class com.fazecast.jSerialComm.SerialPortEvent
    }
   }




  GraphViewer -up-|> JFrame
  MapGraph -up-|> edu.uci.ics.jung.graph.SparseMultigraph
   WriteThread -up-|> Thread
   MonitorThread -up-|> Thread
   SeriaListener .up.|> com.fazecast.jSerialComm.SerialPortPacketListener

   GraphViewer o-up- Dimension:m_dimension
   GraphViewer o-up- VisualizationViewer: m_vv
   GraphViewer o-up- StaticLayout: m_layout

   MapGraph o-up- edu.uci.ics.jung.graph.Graph


    MessagePayload +-right- MessagePayloadBuilder
    MessagePayload +-down- CommsProperties:cmds
  MessageRecordParser o-- MessagePayload : m_messagePayload

  MessageRecordQueue o-- SerialMessageRecord: m_queue

  MonitorThread o-- MessageRecordQueue : m_queue
  MonitorThread o-- MessageRecordParser : m_parser
  MonitorThread o-- WriteThread : m_writeThread

  MessagePayloadBuilder o.left. MessagePayload

  SeriaListener o-- MessageRecordParser : m_parser
  SeriaListener o-- MessageRecordQueue : m_queue
  SeriaListener o-- com.fazecast.jSerialComm.SerialPortEvent
  WriteThread o-- MessageRecordQueue : m_queue
  WriteThread o-- MessageRecordParser : m_parser
  WriteThread o-- MessagePayloadBuilder : m_MPB
  MainRobot o-- WriteThread: m_writeThread
  MainRobot o-- MonitorThread : m_monitorThread
  MainRobot o-- com.fazecast.jSerialComm.SerialPort: m_comPort
  MainRobot o-- MessageRecordQueue: m_queue


right footer



endfooter

@enduml
